#!/bin/bash

source ./Configuration

printf "\nCleaning up old Install files if needed\n"
./clean yes

printf "\nSetting up new local virtual environment using python located in $PYTHON\n"
# set up virtual environment
virtualenv -p $PYTHON .

printf "\nsourcing the new virtual environment."
printf "\nTo use this installation in the future, you will need to call source bin/activate\n"
source bin/activate

#easy_install psycopg2==2.6.1
#easy_install sqlalchemy==1.0.8
#easy_install markupsafe
#easy_install sqlparse
#easy_install Flask
#easy_install Flask-SQLAlchemy
#easy_install Flask-Admin
#easy_install Flask-JSON
#easy_install flask_login
#easy_install flask-restplus
#pip install --upgrade jsonschema
#easy_install marshmallow
#easy_install Flask-Cache
#easy_install python-pam
#easy_install wtforms
#easy_install cherrypy==6.2.0
#pip install --upgrade jsonschema
#easy_install natsort
#easy_install watchdog

pip install -r requirements.txt

printf "\nInstalling mgipython library \n"
python setup.py install --record installed_files.txt

#printf "\nRunning unit tests \n"
#cd tests
#python all_tests.py
#if [ $? -ne 0 ]; then
#	printf "\nUnit tests failed \n"
#        exit 1
#fi
